<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.joshlong</groupId>
    <artifactId>bitwarden-cli-client</artifactId>
    <version>0.0.2</version>
    <name>
        A Bitwarden CLI Wrapper
    </name>
    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>


    <description>
        Provides a convient autoconfiguration and client to the Bitwarden CLI. Ideal for use in, e.g. JBang
        shell scripts or other such things.
    </description>
    <url>
        https://github.com/joshlong/bitwarden-java-client/
    </url>

    <developers>
        <developer>
            <name>Josh Long</name>
            <email>josh@joshlong.com</email>
            <organization>joshlong.com</organization>
            <organizationUrl>https://github.com/joshlong/bitwarden-java-client</organizationUrl>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:git://github.com/joshlong/bitwarden-java-client.git</connection>
        <developerConnection>scm:git:ssh://github.com/joshlong/bitwarden-java-client.git
        </developerConnection>
        <url>https://github.com/joshlong/bitwarden-java-client/tree/main</url>
    </scm>


    <properties>
        <java.version>25</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-restclient</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.spring.javaformat</groupId>
                <artifactId>spring-javaformat-maven-plugin</artifactId>
                <version>0.0.48</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <inherited>true</inherited>
                        <goals>
                            <goal>validate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>publish</id>
            <properties>
                <altDeploymentRepository>local::file:./target/staging-deploy</altDeploymentRepository>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <version>3.2.1</version>
                        <executions>
                            <execution>
                                <id>attach-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <version>3.11.1</version>
                        <executions>
                            <execution>
                                <id>attach-javadocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.jreleaser</groupId>
                        <artifactId>jreleaser-maven-plugin</artifactId>
                        <version>1.21.0</version>
                        <configuration>
                            <jreleaser>
                                <release>
                                    <github>
                                        <branch>main</branch>
                                    </github>
                                </release>
                                <signing>
                                    <active>ALWAYS</active>
                                    <armored>true</armored>
                                    <mode>FILE</mode>
                                    <publicKey>${user.home}/.jreleaser/public</publicKey>
                                    <secretKey>${user.home}/.jreleaser/private</secretKey>
                                </signing>
                                <deploy>
                                    <maven>
                                        <mavenCentral>
                                            <maven-central>
                                                <active>ALWAYS</active>
                                                <url>https://central.sonatype.com/api/v1/publisher</url>
                                                <stagingRepositories>target/staging-deploy</stagingRepositories>
                                            </maven-central>
                                        </mavenCentral>
                                    </maven>
                                </deploy>
                            </jreleaser>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
